"""empty message

Revision ID: 65ad8290730f
Revises: cd725c852abd
Create Date: 2017-04-30 20:52:28.443999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ad8290730f'
down_revision = 'cd725c852abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_id', sa.String(length=30), nullable=False),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisor_id'), 'advisor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisor_id'), table_name='advisor')
    op.drop_table('advisor')
    # ### end Alembic commands ###
