"""empty message

Revision ID: cd725c852abd
Revises: 
Create Date: 2017-04-19 22:39:17.875678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd725c852abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_id', sa.String(length=30), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('specialization_ug', sa.String(length=30), nullable=True),
    sa.Column('institution_ug', sa.String(length=30), nullable=True),
    sa.Column('degree_ug', sa.String(length=30), nullable=True),
    sa.Column('cgpa_ug', sa.Float(), nullable=True),
    sa.Column('specialization_12', sa.String(length=30), nullable=True),
    sa.Column('institution_12', sa.String(length=30), nullable=True),
    sa.Column('board_12', sa.String(length=30), nullable=True),
    sa.Column('marks_12', sa.Integer(), nullable=True),
    sa.Column('specialization_10', sa.String(length=30), nullable=True),
    sa.Column('institution_10', sa.String(length=30), nullable=True),
    sa.Column('board_10', sa.String(length=30), nullable=True),
    sa.Column('marks_10', sa.Integer(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('roll_number'),
    sa.UniqueConstraint('email_id')
    )
    op.create_index(op.f('ix_student_roll_number'), 'student', ['roll_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_roll_number'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
