"""empty message

Revision ID: d60a2a9f6487
Revises: a22f7b990931
Create Date: 2017-05-01 01:48:19.655512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60a2a9f6487'
down_revision = 'a22f7b990931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('aptitude_advisor_id', sa.String(length=30), nullable=True))
    op.add_column('batch', sa.Column('ssk_advisor_id', sa.String(length=30), nullable=True))
    op.add_column('batch', sa.Column('verbal_advisor_id', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'batch', 'advisor', ['ssk_advisor_id'], ['employee_id'])
    op.create_foreign_key(None, 'batch', 'advisor', ['aptitude_advisor_id'], ['employee_id'])
    op.create_foreign_key(None, 'batch', 'advisor', ['verbal_advisor_id'], ['employee_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'verbal_advisor_id')
    op.drop_column('batch', 'ssk_advisor_id')
    op.drop_column('batch', 'aptitude_advisor_id')
    # ### end Alembic commands ###
